export const data = [
  {
    id: "recZkNf2kwmdBcqd0",
    title: "Naruto",
    img: "https://upload.wikimedia.org/wikipedia/en/9/94/NarutoCoverTankobon1.jpg",
    rate: "8",
    date: " 20 septembre 1999 ",
  },
  {
    id: "recZkNf2kwmdBc5548",
    title: "kimetsu no yaiba",
    img: "https://www.theanimex.com/wp-content/uploads/2022/04/Demon-Slayer-Kimetsu-no-Yaiba-Stories-of-Water-and-Flame.jpg",
    rate: "7",
    date: "6 avril 2019",
  },

  {
    id: "recZkN554wmdBcqd0",
    title: "One Piece",
    img: "https://static.tvtropes.org/pmwiki/pub/images/2e5c6d37_566f_4274_b62d_ebf5fcbd0722.png",
    rate: "9",
    date: "22 juillet 1997",
  },
  {
    id: "r658ZkNf2kwmdBcqd0",
    title: "jujutsu kaisen",
    img: "https://images.epagine.fr/883/9791032707883_1_75.jpg",
    rate: "7",
    date: "28 avril 2017",
  },
  {
    id: "recZkNf454wmdBcqd0",
    title: "Attack on Titan",
    img: "https://www.dvdfr.com/images/sagas/l_attaque_des_titans/b8342a2f39ae1fa4b4c3c720da8af419/poster.small.tvdb.jpg",
    rate: "8",
    date: "septembre 2009",
  },
  {
    id: "recZkNf2ghjdBcqd0",
    title: "nanatsu no taizai",
    img: "https://wallpapercave.com/wp/wp2414214.jpg",
    rate: "6",
    date: "2 juillet 2021",
  },
  {
    id: "recZkNf2kwmghjkll0",
    title: "Baki",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUW8qhj9ueMiWyYODWfvPNAQRjzL-6puTPwqGyVrJCCG5jST8JMoBy64NDRHK6FZSGsHA&usqp=CAU",
    rate: "6",
    date: "octobre 1991",
  },
  {
    id: "recZfghgffkwmdBcqd0",
    title: "Black Clover",
    img: "https://upload.wikimedia.org/wikipedia/en/6/69/Black_Clover%2C_volume_1.jpg",
    rate: "9,9",
    date: "16 février 2015",
  },
  {
    id: "recZkNf2khhggmdBcqd0",
    title: "Tokita",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG35ESIaymrAdMwksrawckuuZ2Xyjw8EpsoQ&usqp=CAU",
    rate: "6",
    date: "31 juillet 2019",
  },
  {
    id: "recghjk2kwmdBcqd0",
    title: "Death note",
    img: "https://www.manga-news.com/public/images/series/death_note_01.jpg",
    rate: "8",
    date: "mai 2004",
  },
];
