export const data = [
  {
    id: "5001",
    src: "https://youtu.be/KPLWWIOCOOQ",
    title: "Game Of Thrones",
    img: "https://fr.web.img6.acsta.net/pictures/19/03/21/17/05/1927893.jpg",
    category: "fantasy drama",
    rate: "9",
    cast: " David Benioff",
    date: "17 avril 2011",
  },
  {
    id: "5002",
    src: "https://youtu.be/1JLUn2DFW4w",
    title: "Breaking Bad",
    img: "https://fr.web.img5.acsta.net/pictures/19/06/18/12/11/3956503.jpg",
    category: "crime drama",
    rate: "10",
    cast: "Vince Gilligan.",
    date: "20 janvier 2008",
  },
  {
    id: "5003",
    src: "https://youtu.be/xSR4dNmJtS0",
    title: "The Vampire Diaries",
    img: "https://flxt.tmsimg.com/assets/p8182631_b1t_v9_aa.jpg",
    category: "comedy drama teen",
    rate: "7",
    cast: " Kevin Williamson",
    date: " 10 septembre 2009",
  },
  {
    id: "5004",
    src: "https://youtu.be/7XEQqaV_dTM",
    title: "The Originals",
    img: "https://m.media-amazon.com/images/M/MV5BNDllZjc2NjEtOGMwZS00ZmNkLTg2NDgtZjJkYjg0YjMxM2FmXkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_.jpg",
    category: "fantasy-drama",
    rate: "8",
    cast: " Julie Plec",
    date: "3 octobre 2013",
  },
  {
    id: "5005",
    src: "https://youtu.be/xHHM5VTATJo",
    title: "Legacies",
    img: "https://fr.web.img6.acsta.net/pictures/21/08/30/17/35/5936439.jpg",
    category: "fantasy-drama",
    rate: "6",
    cast: ". Matt Davis",
    date: "25 octobre 2018",
  },
  {
    id: "5006",
    src: "https://youtu.be/vgg9nnALFGA",
    title: "Da Vinci's Demons",
    img: "https://m.media-amazon.com/images/M/MV5BYzA5YjY2ZmUtODliNS00ZjhlLTkwZjItODNmYzQ3MDc0YThlXkEyXkFqcGdeQXVyOTQxNzM2MjY@._V1_.jpg",
    category: "historical fantasy",
    rate: "7",
    cast: " David S. Goyer",
    date: "12 April 2013",
  },
  {
    id: "5007",
    src: "https://youtu.be/9GgxinPwAGc",
    title: "Vikings",
    img: "https://m.media-amazon.com/images/M/MV5BODk4ZjU0NDUtYjdlOS00OTljLTgwZTUtYjkyZjk1NzExZGIzXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
    category: "historical fantasy",
    rate: "8",
    cast: " jarl Haraldson,",
    date: "3 mars 2013",
  },
  {
    id: "5008",
    src: "https://youtu.be/oqxAJKy0ii4",
    title: "Squid Game",
    img: "https://m.media-amazon.com/images/M/MV5BYWE3MDVkN2EtNjQ5MS00ZDQ4LTliNzYtMjc2YWMzMDEwMTA3XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    category: "historical fantasy",
    rate: "6",
    cast: "Hwang Dong-hyuk",
    date: "21 octobre 2021",
  },
  {
    id: "5009",
    src: "https://youtu.be/sfAc2U20uyg",
    title: "The Walking Dad",
    img: "https://m.media-amazon.com/images/M/MV5BZmU5NTcwNjktODIwMi00ZmZkLTk4ZWUtYzVjZWQ5ZTZjN2RlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY1200_CR83,0,630,1200_AL_.jpg",
    category: "historical fantasy",
    rate: "9",
    cast: " Frank Darabont",
    date: "2010",
  },
  {
    id: "5010",
    src: "https://youtu.be/UaVTIH8mujA",
    title: "The Godfather",
    img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    category: "fantasy-drama",
    rate: "10",
    cast: " Francis Ford Coppola",
    date: "1972",
  },
  {
    id: "5011",
    src: "https://youtu.be/aDrsItJ_HU4",
    title: "The 100",
    img: "https://m.media-amazon.com/images/I/51LYrVg7iRL._AC_SY445_.jpg",
    category: "fantasy-drama",
    rate: "7",
    cast: "Jason Rothenberg",
    date: "2014",
  },
  {
    id: "5012",
    src: "https://youtu.be/ndl1W4ltcmg",
    title: "The Witcher",
    img: "https://image.api.playstation.com/vulcan/ap/rnd/202211/0714/S1jCzktWD7XJSRkz4kNYNVM0.png",
    category: "fantasy-drama",
    rate: "8",
    cast: " Lauren Schmidt Hissrich",
    date: "2019",
  },
];
